# Generated by Django 6.0.1 on 2026-01-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='user_name',
            new_name='username',
        ),
    ]
